const express = require('express');
const helmet = require('helmet');
const morgan = require('morgan');
const path = require('path');
const globalErrorHandler = require('./controller/errorController');
const userRouter = require('./routes/userRouter');
const postRouter = require('./routes/postRouter');
const commentRouter = require('./routes/commentRouter');
const likeRouter = require('./routes/likeRouter');
const donation_requestRouter = require('./routes/donation_requestRouter');
const organizationRouter = require('./routes/organizationRouter');
const donationCampaignRouter = require('./routes/donationCampaignRouter');
const followingRouter = require('./routes/followingRouter');
const followerRouter = require('./routes/followerRouter');
const AppError = require('./utils/appError');
const app = express();
app.use((req, res, next) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PATCH, DELETE');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  next();
});
app.use(helmet());
app.use(express.json({ limit: '10kb' }));
app.set('view engine', 'ejs');
app.set('views', path.join(__dirname, 'views'));
app.use(express.static(path.join(__dirname, 'public')));
app.use(morgan('common'));
app.use('/api/posts', postRouter);
app.use('/api/users', userRouter);
app.use('/api/comments', commentRouter);
app.use('/api/likes', likeRouter);
app.use('/api/donation_requests', donation_requestRouter);
app.use('/api/organizations', organizationRouter);
app.use('/api/donationCampaigns', donationCampaignRouter);
app.use('/api/followings', followingRouter);
app.use('/api/followers', followerRouter);
app.all('*', (req, res, next) => {
  next(new AppError(`can't find ${req.originalUrl} on server!`, 404));
});
app.use(globalErrorHandler);
module.exports = app;
